### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [pearmans/project9#1]
My login information doesn't seem to be working on Heroku. Did you add that user to Heroku's database as well?

**Comment by stuartpearman** [comment]
I think I know what's going on. I turned in last week's project and
replaced the Heroku app with this week's project without thinking about it
because of how late I finished it. I have added account information for
myself but I got interrupted when I was going to add yours. I'll be done
with that tonight though. I'll turn the authentication project into
codekwondo when I'm finished, sorry for the inconvenience!

**Comment by stuartpearman** [comment]
I just updated it so that your login information will work, but I just
realized there isn't a greeting with your email information when the user
logs in. But you should be able to at least grade last week's project after
the recent changes. If you want me to host the previous project on heroku
just let me know and I can host another app.

Thanks!
Stuart

**Comment by chrisvfritz** [comment]
OK, now there are just a couple more items I'd like dealt with:
- It looks like [a hard tab snuck in here](https://github.com/pearmans/project9/blob/master/app/models/task.rb#L2). Can you update this to a two-space soft tab?
- There's a field called `Days`, but it looks like we can only put in a single day (though I do love the date picker!). Is this mislabeled?
- Do we want to validate that tasks aren't assigned to days in the past?
- It looks like the `duration` field isn't actually setting when I create a new task (though it _does_ work when I update a task).

**Comment by chrisvfritz** [comment]
One other note, though this isn't something you have to address, is a reformat of lines [like this](https://github.com/pearmans/project9/blob/master/app/views/tasks/_form.html.slim#L4) in Slim:

``` slim
h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
```

Whenever you have regular text or HTML that you'd like to mix Ruby into, you can just leave off the `=` (which makes the whole line Ruby), then you don't have to wrap everything in quotes to make it a string. Instead, you can simply write:

``` slim
h2 #{pluralize(@task.errors.count, "error")} prohibited this task from being saved:
```

**Comment by stuartpearman** [comment]
I updated the repo and Heroku app with those changes, however I didn't
remember to reformat the redundant line of slim.

See you tomorrow!

**Comment by chrisvfritz** [comment]
:+1: Wonderful!
